const settingsActionTypes =  {    
    SWITCH_TAB: "SWITCH_TAB",
    RETRIEVED_SETTINGS: "RETRIEVED_SETTINGS",
    UPDATED_SETTINGS: "UPDATED_SETTINGS",
    SETTINGS_CLIENT_MODIFIED: "SETTINGS_CLIENT_MODIFIED",
    RETRIEVED_PROFILESETTINGS: "RETRIEVED_PROFILESETTINGS",
    CANCELLED_PROFILEMAPPING_CLIENT_MODIFIED: "CANCELLED_PROFILEMAPPING_CLIENT_MODIFIED",
    PROFILEMAPPINGS_CLIENT_MODIFIED: "PROFILEMAPPINGS_CLIENT_MODIFIED"
};
export default settingsActionTypes;